spring.application.name=expensetracker

spring.datasource.url=jdbc:mysql://localhost:3306/expensetracker_db
spring.datasource.username=root
spring.datasource.password=jaswaltanish248@gmail.com
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}